name: primetag_task
description: "A new Flutter project."

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.8
  flutter_bloc: ^9.1.0
  equatable: ^2.0.7
  get_it: ^8.0.3
  dio: ^5.8.0+1
  pretty_dio_logger: ^1.4.0
  dartz: ^0.10.1
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  freezed_annotation: ^3.0.0
  json_annotation: ^4.9.0



dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.4.15
  freezed:
  json_serializable:
  hive_generator: ^2.0.1



flutter:
  uses-material-design: true
